"""Init

Revision ID: 142956e49fa0
Revises: 
Create Date: 2026-06-11 10:24:48.325565

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '142956e49fa0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ab_group_role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_group_id'))
        batch_op.drop_index(batch_op.f('idx_group_role_id'))

    op.drop_table('ab_group_role')
    with op.batch_alter_table('ab_api_key', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_api_key_lookup_hash'))
        batch_op.drop_index(batch_op.f('idx_api_key_prefix'))
        batch_op.drop_index(batch_op.f('idx_api_key_user_id'))

    op.drop_table('ab_api_key')
    with op.batch_alter_table('ab_permission_view_role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_permission_view_id'))
        batch_op.drop_index(batch_op.f('idx_role_id'))

    op.drop_table('ab_permission_view_role')
    op.drop_table('ab_register_user')
    op.drop_table('ab_user_role')
    op.drop_table('ab_user')
    with op.batch_alter_table('ab_permission_view', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_permission_id'))
        batch_op.drop_index(batch_op.f('idx_view_menu_id'))

    op.drop_table('ab_permission_view')
    op.drop_table('ab_group')
    with op.batch_alter_table('ab_user_group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_group_id'))
        batch_op.drop_index(batch_op.f('idx_user_id'))

    op.drop_table('ab_user_group')
    op.drop_table('ab_role')
    op.drop_table('ab_permission')
    op.drop_table('ab_view_menu')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ab_view_menu',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ab_view_menu_pkey')),
    sa.UniqueConstraint('name', name=op.f('ab_view_menu_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('ab_permission',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ab_permission_pkey')),
    sa.UniqueConstraint('name', name=op.f('ab_permission_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('ab_role',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ab_role_pkey')),
    sa.UniqueConstraint('name', name=op.f('ab_role_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('ab_user_group',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['ab_group.id'], name=op.f('ab_user_group_group_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['ab_user.id'], name=op.f('ab_user_group_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ab_user_group_pkey')),
    sa.UniqueConstraint('user_id', 'group_id', name=op.f('ab_user_group_user_id_group_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('ab_user_group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_group_id'), ['group_id'], unique=False)

    op.create_table('ab_group',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('ab_group_pkey')),
    sa.UniqueConstraint('name', name=op.f('ab_group_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('ab_permission_view',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('view_menu_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['ab_permission.id'], name=op.f('ab_permission_view_permission_id_fkey')),
    sa.ForeignKeyConstraint(['view_menu_id'], ['ab_view_menu.id'], name=op.f('ab_permission_view_view_menu_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ab_permission_view_pkey')),
    sa.UniqueConstraint('permission_id', 'view_menu_id', name=op.f('ab_permission_view_permission_id_view_menu_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('ab_permission_view', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_view_menu_id'), ['view_menu_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_permission_id'), ['permission_id'], unique=False)

    op.create_table('ab_user',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('login_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fail_login_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('changed_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by_fk', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('changed_by_fk', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], name=op.f('ab_user_changed_by_fk_fkey')),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], name=op.f('ab_user_created_by_fk_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ab_user_pkey')),
    sa.UniqueConstraint('email', name=op.f('ab_user_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name=op.f('ab_user_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('ab_user_role',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['ab_role.id'], name=op.f('ab_user_role_role_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['ab_user.id'], name=op.f('ab_user_role_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ab_user_role_pkey')),
    sa.UniqueConstraint('user_id', 'role_id', name=op.f('ab_user_role_user_id_role_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('ab_register_user',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=False),
    sa.Column('registration_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('registration_hash', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('ab_register_user_pkey')),
    sa.UniqueConstraint('email', name=op.f('ab_register_user_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name=op.f('ab_register_user_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('ab_permission_view_role',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_view_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['permission_view_id'], ['ab_permission_view.id'], name=op.f('ab_permission_view_role_permission_view_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['ab_role.id'], name=op.f('ab_permission_view_role_role_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ab_permission_view_role_pkey')),
    sa.UniqueConstraint('permission_view_id', 'role_id', name=op.f('ab_permission_view_role_permission_view_id_role_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('ab_permission_view_role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_permission_view_id'), ['permission_view_id'], unique=False)

    op.create_table('ab_api_key',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('key_hash', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('lookup_hash', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('key_prefix', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scopes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expires_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('revoked_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_used_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['ab_user.id'], name=op.f('ab_api_key_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ab_api_key_pkey')),
    sa.UniqueConstraint('lookup_hash', name=op.f('ab_api_key_lookup_hash_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('uuid', name=op.f('ab_api_key_uuid_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('ab_api_key', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_api_key_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_api_key_prefix'), ['key_prefix'], unique=False)
        batch_op.create_index(batch_op.f('idx_api_key_lookup_hash'), ['lookup_hash'], unique=True)

    op.create_table('ab_group_role',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['ab_group.id'], name=op.f('ab_group_role_group_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['ab_role.id'], name=op.f('ab_group_role_role_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ab_group_role_pkey')),
    sa.UniqueConstraint('group_id', 'role_id', name=op.f('ab_group_role_group_id_role_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('ab_group_role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_group_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_group_id'), ['group_id'], unique=False)

    # ### end Alembic commands ###
